## joint_names
# This is used by cob_control_mode_adapter
# This is loaded at https://github.com/ipa320/cob_control/blob/f2116ffc9fbb924e5cb18ee21905434673068f63/cob_control_mode_adapter/src/cob_control_mode_adapter_node.cpp#L85
# Since we don't use cob_control_mode_adapter, we won't include this parameter.
# However, in simulation, without this param, /arm/joint_states won't work. So we have to keep it.
joint_names: [arm_shoulder_pan_joint, arm_shoulder_lift_joint, arm_elbow_joint, arm_wrist_1_joint, arm_wrist_2_joint, arm_wrist_3_joint]

## control_mode_adapter
max_command_silence: 0.5

# This is used for ur_modern_driver
# https://github.com/Shentheman/ur_modern_driver/blob/irg/config/ur10_controllers.yaml

# Settings for ros_control control loop
hardware_control_loop:
   loop_hz: 125

# Settings for ros_control hardware interface
hardware_interface:
   joints:
     - arm_shoulder_pan_joint
     - arm_shoulder_lift_joint
     - arm_elbow_joint
     - arm_wrist_1_joint
     - arm_wrist_2_joint
     - arm_wrist_3_joint

# Publish all joint states ----------------------------------
joint_state_controller:
   type:         joint_state_controller/JointStateController
   publish_rate: 125

# Publish wrench ----------------------------------
force_torque_sensor_controller:
   type:         force_torque_sensor_controller/ForceTorqueSensorController
   publish_rate: 125

# Joint Trajectory Controller - position based -------------------------------
# For detailed explanations of parameter see http://wiki.ros.org/joint_trajectory_controller
pos_based_pos_traj_controller:
   type: position_controllers/JointTrajectoryController
   joints:
     - arm_shoulder_pan_joint
     - arm_shoulder_lift_joint
     - arm_elbow_joint
     - arm_wrist_1_joint
     - arm_wrist_2_joint
     - arm_wrist_3_joint
   constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      arm_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
      arm_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
      arm_elbow_joint: {trajectory: 0.1, goal: 0.1}
      arm_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
      arm_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
      arm_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
   stop_trajectory_duration: 0.5
   state_publish_rate:  125
   action_monitor_rate: 10

   # state_publish_rate:  50 # Defaults to 50
   # action_monitor_rate: 20 # Defaults to 20
   #hold_trajectory_duration: 0 # Defaults to 0.5
   
# Joint Trajectory Controller -------------------------------
# For detailed explanations of parameter see http://wiki.ros.org/joint_trajectory_controller
vel_based_pos_traj_controller:
   type: velocity_controllers/JointTrajectoryController
   joints:
     - arm_shoulder_pan_joint
     - arm_shoulder_lift_joint
     - arm_elbow_joint
     - arm_wrist_1_joint
     - arm_wrist_2_joint
     - arm_wrist_3_joint
   constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      arm_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
      arm_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
      arm_elbow_joint: {trajectory: 0.1, goal: 0.1}
      arm_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
      arm_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
      arm_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
   stop_trajectory_duration: 0.5
   state_publish_rate:  125
   action_monitor_rate: 10
   gains:
       #!!These values are useable, but maybe not optimal
      arm_shoulder_pan_joint: {p: 5.5,  i: 0.0, d: 0.15, i_clamp: 1}
      arm_shoulder_lift_joint: {p: 5.5,  i: 0.0, d: 0.15, i_clamp: 1}
      arm_elbow_joint: {p: 5.5,  i: 0.0, d: 0.15, i_clamp: 1}
      arm_wrist_1_joint: {p: 5.5,  i: 0.0, d: 0.15, i_clamp: 1}
      arm_wrist_2_joint: {p: 5.5,  i: 0.0, d: 0.15, i_clamp: 1}
      arm_wrist_3_joint: {p: 5.5,  i: 0.0, d: 0.15, i_clamp: 1}


   # state_publish_rate:  50 # Defaults to 50
   # action_monitor_rate: 20 # Defaults to 20
   #hold_trajectory_duration: 0 # Defaults to 0.5


## Direct position controller
joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
     - arm_shoulder_pan_joint
     - arm_shoulder_lift_joint
     - arm_elbow_joint
     - arm_wrist_1_joint
     - arm_wrist_2_joint
     - arm_wrist_3_joint

arm_shoulder_pan_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: arm_shoulder_pan_joint
arm_shoulder_lift_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: arm_shoulder_lift_joint
arm_elbow_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: arm_elbow_joint
arm_wrist_1_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: arm_wrist_1_joint
arm_wrist_2_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: arm_wrist_2_joint
arm_wrist_3_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: arm_wrist_3_joint


# universal_robot https://github.com/ros-industrial/universal_robot does not support velocity control.
## Direct velocity controller
joint_group_velocity_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
     - arm_shoulder_pan_joint
     - arm_shoulder_lift_joint
     - arm_elbow_joint
     - arm_wrist_1_joint
     - arm_wrist_2_joint
     - arm_wrist_3_joint

arm_shoulder_pan_joint_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: arm_shoulder_pan_joint
arm_shoulder_lift_joint_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: arm_shoulder_lift_joint
arm_elbow_joint_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: arm_elbow_joint
arm_wrist_1_joint_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: arm_wrist_1_joint
arm_wrist_2_joint_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: arm_wrist_2_joint
arm_wrist_3_joint_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: arm_wrist_3_joint
